version: '3'
services:
  mysql:
    image: mysql:5.7.26
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASS: "root"
  insta:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/docker_insta_task
    ports:
      - "3000:3000"
    depends_on:
      - mysql
