version: '3'
services:
  mysql:
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    # ports:
    #   - "3306:3306"
  redis:
    image: redis
  elasticsearch:
    image: elasticsearch:6.4.0
    # ports:
    #   - "9200:9200"
    restart: always
  insta:
    build: .
    command: sh ./start.sh
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - elasticsearch
      - mysql
