version: '3'
services:
  mysql:
    image: mysql:5.7.26
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insta-task_development
    ports:
      - "3306:3306"
  insta:
    build: .
    command: bash -c "rake db:create && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/docker_insta_task
    ports:
      - "3000:3000"
    depends_on:
      - mysql
