:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
:schedule:
  ChatCounterUpdaterWorker:
    every: '30m'
  MessageCounterUpdaterWorker:
    every: '45m'
  MessageReindexWorker:
    in: '10s'